export const projectsData = {
  desenvolvimento: [
    {
      title: "Pet Clini",
      desc: "Landing Page estática para pet shop, desenvolvida apenas com foco em design responsivo e experiência do usuário",
      color: "neonGreen",
      link: "",
      soon: true,
      category: "Landing Page",
      image: "",
      techs: ["React", "TailwindCSS"],
      code: "",
    },
  ],
  recentes: [
    {
      title: "Portfólio Dev",
      desc: "Site pessoal interativo para apresentar meus projetos e evolução como desenvolvedor, com design futurista e animações dinâmicas",
      color: "neonPurple",
      link: "https://portfoliorayckacastro.netlify.app/",
      category: "Site Completo",
      image: "/home_port.png",
      techs: ["React", "TailwindCSS"],
    },
    {
      title: "Delícias no Pote 2.0",
      desc: "Sistema de catálogo digital com painel administrativo e CRUD completo, permitindo gestão de produtos em tempo real",
      color: "neonPink",
      link: "https://deliciasnopoterm.netlify.app",
      category: "Site Completo",
      image: "/home_del.png",
      techs: ["React", "Supabase", "TailwindCSS"],
      code: "https://github.com/Rayck4dev/Cardapio-Digital_2.0",
    },
  ],
  landing: [
    {
      title: "Pet Clini",
      desc: "Landing Page estática para pet shop, desenvolvida apenas com foco em design responsivo e experiência do usuário",
      color: "neonGreen",
      link: "",
      soon: true,
      category: "Landing Page",
      image: "",
      techs: ["React", "TailwindCSS"],
      code: "",
    },
    {
      title: "Blog Elite Vougue",
      desc: "Blog desenvolvido para treinar habilidades em HTML5, CSS3 e JS",
      color: "neonBlue",
      soon: false,
      category: "Landing Page",
      image: "/home_blog.png",
      techs: ["HTML5", "CSS3", "JavaScript"],
      code: "https://github.com/Rayck4dev/blog-EliteVougue",
    },
  ],
  academicos: [
    {
      title: "Eventix",
      desc: "Plataforma acadêmica inspirada no Sympla, com 2 versões desencolvida para as matérias de DAPI e FRONTEND-FRAMEWORKS",
      color: "neonOrange",
      category: "Trabalho Acadêmico",
      image: "/home_Eventix.png",
      techs: ["CSS3", "HTML5", "JavaScript", "React", "Supabase", "API REST"],
      code: "https://github.com/Rayck4dev/Projeto_Eventix",
    },

    {
      title: "Delícias no Pote 1.0",
      desc: "Primeira versão do catálogo digital, Delícias no Pote desenvolvida como projeto de extensão",
      color: "neonPink",
      link: "https://deliciasnopote.netlify.app/",
      soon: false,
      category: "Landing Page",
      image: "/home_del1.png",
      techs: ["HTML5", "CSS3", "JavaScript", "Canva"],
      code: "https://github.com/Rayck4dev/Projeto_Cardapio-Digital",
    },
    {
      title: "Sistema de Pedágio",
      desc: "Aplicação em Java que simula o funcionamento de um pedágio, com lógica de cobrança e relatórios, desenvolvida para a disciplina de POO",
      color: "neonOrange",
      category: "Trabalho Acadêmico",
      image: "/code_java.png",
      techs: ["Java"],
      code: "https://github.com/Rayck4dev/Atividades-Java_Facul/tree/Trabalho-Ped%C3%A1gio-2025",
    },
  ],
  completos: [
    {
      title: "Portfólio Dev",
      desc: "Site pessoal interativo para apresentar meus projetos e evolução como desenvolvedor, com design futurista e animações dinâmicas",
      color: "neonPurple",
      link: "https://portfoliorayckacastro.netlify.app/",
      category: "Site Completo",
      image: "/home_port.png",
      techs: ["React", "TailwindCSS"],
    },
    {
      title: "Delícias no Pote 2.0",
      desc: "Sistema de catálogo digital com painel administrativo e CRUD completo, permitindo gestão de produtos em tempo real",
      color: "neonPink",
      link: "https://deliciasnopoterm.netlify.app",
      category: "Site Completo",
      image: "/home_del.png",
      techs: ["React", "Supabase", "TailwindCSS"],
      code: "https://github.com/Rayck4dev/Cardapio-Digital_2.0",
    },
  ],
};
