export const projectsData = {
  desenvolvimento: [
    {
      title: "ShopSmart App",
      desc: "Aplicativo mobile para compra e venda de produtos, desenvolvido para a disciplina de Desenvolvimento Mobile",
      color: "neonYellow",
      soon: true,
      category: "Trabalho Acadêmico",
      image: "",
      techs: ["Mobile", "TypeScript", "React Native", "TailwindCSS", "Supabase", "API REST"],
      code: "https://github.com/Rayck4dev/ShopSmart-App",
    },
    {
      title: "HandStark",
      desc: "Projeto de IA para detecção de gestos e comandos, além de resolução de particulas em tempo real",
      color: "neonBlue",
      soon: true,
      category: "Outros",
      image: "",
      techs: ["Python", "Nextjs", "TailwindCSS", "API REST", "Mediapipe"],
      code: "",
    },
  ],

  recentes: [
    {
      title: "LinkTree para Piscicultura",
      desc: "Aplicação web moderna para apresentar catálogo de peixes, contatos e informações da piscicultura de forma simples e intuitiva",
      color: "neonGreen",
      link: "https://pisciculturamagraoalevinos.netlify.app/",
      category: "Site Completo",
      image: "home_fish.png",
      techs: ["React", "TailwindCSS", "JavaScript"],
      code: "https://github.com/Rayck4dev/piscicultura-linktree",
    },
    {
      title: "Dashboard de Filmes",
      desc: "Dashboard criado para aprendizado durante a Imersão Alura, com dados reais da API TMDb",
      color: "neonRed",
      link: "https://dashboard-filmes.streamlit.app/",
      category: "Outros",
      image: "home_dash.png",
      techs: ["Python", "API REST", "Pandas", "Plotly", "Streamlit"],
      code: "https://github.com/Rayck4dev/Dashboard_filmes",
    },
  ],

  landing: [
    {
      title: "PetClini",
      desc: "Landing Page estática para pet shop, desenvolvida apenas com foco em design responsivo e experiência do usuário",
      color: "neonGreen",
      soon: false,
      category: "Landing Page",
      image: "home_pet.png",
      techs: ["React", "TailwindCSS"],
      code: "https://github.com/Rayck4dev/Landing-Pages/tree/PetClini",
    },
    {
      title: "Blog Elite Vougue",
      desc: "Blog desenvolvido para treinar habilidades em HTML5, CSS3 e JS",
      color: "neonBlue",
      soon: false,
      category: "Landing Page",
      image: "/home_blog.png",
      techs: ["HTML5", "CSS3", "JavaScript"],
      code: "https://github.com/Rayck4dev/blog-EliteVougue",
    },
  ],

  academicos: [
    {
      title: "Eventix",
      desc: "Plataforma acadêmica inspirada no Sympla, com 2 versões desencolvida para as matérias de DAPI e FRONTEND-FRAMEWORKS",
      color: "neonOrange",
      category: "Trabalho Acadêmico",
      image: "/home_Eventix.png",
      techs: ["CSS3", "HTML5", "JavaScript", "React", "Supabase", "API REST"],
      code: "https://github.com/Rayck4dev/Projeto_Eventix",
    },
    {
      title: "Delícias no Pote 1.0",
      desc: "Primeira versão do catálogo digital, Delícias no Pote desenvolvida como projeto de extensão",
      color: "neonPink",
      link: "https://deliciasnopote.netlify.app/",
      soon: false,
      category: "Landing Page",
      image: "/home_del1.png",
      techs: ["HTML5", "CSS3", "JavaScript"],
      code: "https://github.com/Rayck4dev/Projeto_Cardapio-Digital",
    },
    {
      title: "Sistema de Pedágio",
      desc: "Aplicação em Java que simula o funcionamento de um pedágio, com lógica de cobrança e relatórios, desenvolvida para a disciplina de POO",
      color: "neonOrange",
      category: "Trabalho Acadêmico",
      image: "/code_java.png",
      techs: ["Java"],
      code: "https://github.com/Rayck4dev/Atividades-Java_Facul/tree/Trabalho-Ped%C3%A1gio-2025",
    },
  ],

  outros: [
    {
      title: "LinkTree para Piscicultura",
      desc: "Aplicação web moderna para apresentar catálogo de peixes, contatos e informações da piscicultura de forma simples e intuitiva",
      color: "neonGreen",
      link: "https://pisciculturamagraoalevinos.netlify.app/",
      soon: false,
      category: "Site Completo",
      image: "home_fish.png",
      techs: ["React", "TailwindCSS", "JavaScript"],
      code: "https://github.com/Rayck4dev/piscicultura-linktree",
    },
    {
      title: "Dashboard de Filmes",
      desc: "Dashboard criado para aprendizado durante a Imersão Alura, com dados reais da API TMDb",
      color: "neonRed",
      link: "https://dashboard-filmes.streamlit.app/",
      soon: false,
      category: "Outros",
      image: "home_dash.png",
      techs: ["Python", "API REST", "Pandas", "Plotly", "Streamlit"],
      code: "https://github.com/Rayck4dev/Dashboard_filmes",
    },
    {
      title: "Portfólio Dev",
      desc: "Site pessoal interativo para apresentar meus projetos e evolução como desenvolvedor, com design futurista e animações dinâmicas",
      color: "neonPurple",
      link: "https://portfoliorayckacastro.netlify.app/",
      category: "Site Completo",
      image: "/home_port.png",
      techs: ["React", "TailwindCSS"],
    },
  ],
};
